/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    get: operations["Health"];
  };
  "/api/books": {
    /** List published books, ordered by title, optionally matching a term */
    get: operations["ListBooks"];
  };
  "/api/books/{slug}": {
    /** Read one published book with its chapters */
    get: operations["GetBook"];
  };
  "/api/weatherforecast": {
    get: operations["GetWeatherForecast"];
  };
  "/api/account/antiforgery-token": {
    /** Obtain the antiforgery token for this browser */
    get: operations["GetAntiforgeryToken"];
  };
  "/api/account/password-policy": {
    /** What a password must satisfy */
    get: operations["GetPasswordPolicy"];
  };
  "/api/account/registrations": {
    /** Create an account */
    post: operations["Register"];
  };
  "/api/account/confirmations": {
    /** Confirm an address by redeeming the link sent to it */
    post: operations["ConfirmEmail"];
  };
  "/api/account/confirmation-requests": {
    /** Ask for another confirmation message */
    post: operations["RequestConfirmation"];
  };
  "/api/account/recovery-requests": {
    /** Ask for a link that allows setting a new password */
    post: operations["RequestRecovery"];
  };
  "/api/account/recoveries": {
    /** Set a new password by redeeming a recovery link */
    post: operations["RecoverPassword"];
  };
  "/api/account/session": {
    /** Who this browser is signed in as */
    get: operations["GetSession"];
    /** Sign in */
    post: operations["SignIn"];
    /** Sign out */
    delete: operations["SignOut"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    BookDetail: {
      slug: string;
      title: string;
      authors: string[];
      description: null | string;
      coverArtUrl: null | string;
      language: string;
      /** Format: int32 */
      chapterCount: number;
      /** Format: int32 */
      totalRunningTimeSeconds: number;
      chapters: components["schemas"]["Chapter"][];
    };
    BookSummary: {
      slug: string;
      title: string;
      authors: string[];
      coverArtUrl: null | string;
      /** Format: int32 */
      chapterCount: number;
      /** Format: int32 */
      totalRunningTimeSeconds: number;
    };
    Chapter: {
      /** Format: int32 */
      position: number;
      title: string;
      /** Format: int32 */
      runningTimeSeconds: number;
    };
    ConfirmationResult: {
      outcome: string;
    };
    EmailOnlyRequest: {
      email: null | string;
    };
    HttpValidationProblemDetails: {
      type?: null | string;
      title?: null | string;
      /** Format: int32 */
      status?: null | number;
      detail?: null | string;
      instance?: null | string;
      errors?: {
        [key: string]: string[];
      };
    };
    PagedBooks: {
      items: components["schemas"]["BookSummary"][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      pageSize: number;
      /** Format: int32 */
      totalCount: number;
      /** Format: int32 */
      pageCount: number;
    };
    PasswordPolicyResponse: {
      /** Format: int32 */
      minimumLength: number;
      requiresDigit: boolean;
      requiresUppercase: boolean;
      requiresLowercase: boolean;
      requiresNonAlphanumeric: boolean;
    };
    PasswordResetRequest: {
      /** Format: uuid */
      accountId: string;
      token: null | string;
      password: null | string;
    };
    ProblemDetails: {
      type?: null | string;
      title?: null | string;
      /** Format: int32 */
      status?: null | number;
      detail?: null | string;
      instance?: null | string;
    };
    RegistrationRequest: {
      email: null | string;
      password: null | string;
    };
    SessionResponse: {
      signedIn: boolean;
      email: null | string;
      isVerifiedBeneficiary: boolean;
    };
    SignInRequest: {
      email: null | string;
      password: null | string;
    };
    TokenRequest: {
      /** Format: uuid */
      accountId: string;
      token: null | string;
    };
    WeatherForecast: {
      /** Format: date */
      date: string;
      /** Format: int32 */
      temperatureC: number;
      summary: null | string;
      /** Format: int32 */
      temperatureF?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  Health: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  /** List published books, ordered by title, optionally matching a term */
  ListBooks: {
    parameters: {
      query?: {
        page?: number;
        q?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["PagedBooks"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/problem+json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  /** Read one published book with its chapters */
  GetBook: {
    parameters: {
      path: {
        slug: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["BookDetail"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  GetWeatherForecast: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["WeatherForecast"][];
        };
      };
    };
  };
  /** Obtain the antiforgery token for this browser */
  GetAntiforgeryToken: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  /** What a password must satisfy */
  GetPasswordPolicy: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["PasswordPolicyResponse"];
        };
      };
    };
  };
  /** Create an account */
  Register: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegistrationRequest"];
      };
    };
    responses: {
      /** @description Accepted */
      202: {
        content: never;
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  /** Confirm an address by redeeming the link sent to it */
  ConfirmEmail: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ConfirmationResult"];
        };
      };
      /** @description Gone */
      410: {
        content: {
          "application/problem+json": components["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  /** Ask for another confirmation message */
  RequestConfirmation: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailOnlyRequest"];
      };
    };
    responses: {
      /** @description Accepted */
      202: {
        content: never;
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
    };
  };
  /** Ask for a link that allows setting a new password */
  RequestRecovery: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailOnlyRequest"];
      };
    };
    responses: {
      /** @description Accepted */
      202: {
        content: never;
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
    };
  };
  /** Set a new password by redeeming a recovery link */
  RecoverPassword: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetRequest"];
      };
    };
    responses: {
      /** @description No Content */
      204: {
        content: never;
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
      /** @description Gone */
      410: {
        content: {
          "application/problem+json": components["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  /** Who this browser is signed in as */
  GetSession: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
    };
  };
  /** Sign in */
  SignIn: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignInRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
        };
      };
      /** @description Unauthorized */
      401: {
        content: {
          "application/problem+json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Forbidden */
      403: {
        content: {
          "application/problem+json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Too Many Requests */
      429: {
        content: {
          "application/problem+json": components["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  /** Sign out */
  SignOut: {
    responses: {
      /** @description No Content */
      204: {
        content: never;
      };
    };
  };
}
