/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    get: operations["Health"];
  };
  "/api/books": {
    /** List published books, ordered by title, optionally matching a term */
    get: operations["ListBooks"];
  };
  "/api/books/{slug}": {
    /** Read one published book with its chapters */
    get: operations["GetBook"];
  };
  "/api/weatherforecast": {
    get: operations["GetWeatherForecast"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    BookDetail: {
      slug: string;
      title: string;
      authors: string[];
      description: null | string;
      coverArtUrl: null | string;
      language: string;
      /** Format: int32 */
      chapterCount: number;
      /** Format: int32 */
      totalRunningTimeSeconds: number;
      chapters: components["schemas"]["Chapter"][];
    };
    BookSummary: {
      slug: string;
      title: string;
      authors: string[];
      coverArtUrl: null | string;
      /** Format: int32 */
      chapterCount: number;
      /** Format: int32 */
      totalRunningTimeSeconds: number;
    };
    Chapter: {
      /** Format: int32 */
      position: number;
      title: string;
      /** Format: int32 */
      runningTimeSeconds: number;
    };
    PagedBooks: {
      items: components["schemas"]["BookSummary"][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      pageSize: number;
      /** Format: int32 */
      totalCount: number;
      /** Format: int32 */
      pageCount: number;
    };
    ProblemDetails: {
      type?: null | string;
      title?: null | string;
      /** Format: int32 */
      status?: null | number;
      detail?: null | string;
      instance?: null | string;
    };
    WeatherForecast: {
      /** Format: date */
      date: string;
      /** Format: int32 */
      temperatureC: number;
      summary: null | string;
      /** Format: int32 */
      temperatureF?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  Health: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  /** List published books, ordered by title, optionally matching a term */
  ListBooks: {
    parameters: {
      query?: {
        page?: number;
        q?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["PagedBooks"];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/problem+json": components["schemas"]["ProblemDetails"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  /** Read one published book with its chapters */
  GetBook: {
    parameters: {
      path: {
        slug: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["BookDetail"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/problem+json": components["schemas"]["ProblemDetails"];
        };
      };
    };
  };
  GetWeatherForecast: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["WeatherForecast"][];
        };
      };
    };
  };
}
